### ISSUE TITLE
A JavaScript error occured in the main process

### ISSUE THREAD

**Issue by xolf** [homeworker-app/desktop#1]
Ich habe mir gerade das Projekt ausgecheckt um ein bisschen damit herumzuspielen. Da hab ich folgende Fehler erhalten.

---

**A JavaScript error occured in the main process**
```
Uncaught Exception:
Error: Cannot find module 'electron-push-receiver'
Require stack:
- /Users/flo/Documents/GitHub/desktop/src/main.js
- /Users/flo/Documents/GitHub/desktop/node_modules/electron/dist/Electron.app/Contents/Resources/default_app.asar/main.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:659:15)
    at Function.Module._resolveFilename (/Users/flo/Documents/GitHub/desktop/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/common/reset-search-paths.js:43:12)
    at Function.Module._load (internal/modules/cjs/loader.js:577:27)
    at Module.require (internal/modules/cjs/loader.js:715:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/Users/flo/Documents/GitHub/desktop/src/main.js:2:38)
    at Module._compile (internal/modules/cjs/loader.js:808:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:820:10)
    at Module.load (internal/modules/cjs/loader.js:677:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:609:12)
```

---

Schritte zum Reproduzieren:
1. Projekt auschecken
2. `npm install`
3. `npm run start`

**Comment by rasmuslos** [comment]
Jap, muss den neuen Code noch pushen, hatte vergessen da zu entfernen

**Comment by rasmuslos** [comment]
Fixed #2
